- name: Verify jq installation on target machines
  hosts: all
  gather_facts: true
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Check jq installation and version
      command: jq --version
      register: jq_check
      changed_when: false
      ignore_errors: yes

    - name: Print jq version or missing message
      debug:
        msg: "{{ 'jq is installed: ' ~ jq_check.stdout if jq_check.rc == 0 else 'jq is NOT installed' }}"

    - name: Verify Azure Monitor Agent is installed
      stat:
        path: /opt/microsoft/azuremonitoragent/bin/azuremonitoragent
      register: ama_binary

    - name: Fail if Azure Monitor Agent is not installed
      fail:
        msg: "Azure Monitor Agent is not installed!"
      when: not ama_binary.stat.exists
