- name: Verify jq installation on target machines
  hosts: all
  gather_facts: true
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Check jq installation and version
      command: jq --version
      register: jq_check
      changed_when: false
      ignore_errors: yes

    - name: Print jq version or missing message
      debug:
        msg: "{{ 'jq is installed: ' ~ jq_check.stdout if jq_check.rc == 0 else 'jq is NOT installed' }}"

    - name: Check Artifactory service status
      command: systemctl is-active artifactory
      register: artifactory_service
      ignore_errors: true

    - name: Fail if Artifactory service is not running
      fail:
        msg: "JFrog Artifactory service is not active!"
      when: artifactory_service.stdout != "active"

    - name: Get Artifactory version
      command: /opt/jfrog/artifactory/app/bin/artifactoryManage.sh --version
      register: artifactory_version
      changed_when: false

    - name: Show Artifactory version
      debug:
        msg: "JFrog Artifactory version: {{ artifactory_version.stdout }}"