- name: Verify tools on target machines as a Unit test
  gather_facts: true
  hosts: all
  become: yes

  tasks:
    - name: Check jq installation and version
      command: jq --version
      register: jq_check
      changed_when: false
      failed_when: jq_check.rc != 0

    - name: Print jq version
      debug:
        msg: "jq is installed: {{ jq_check.stdout }}"

    - name: Check curl installation and version
      command: curl --version
      register: curl_check
      changed_when: false
      failed_when: curl_check.rc != 0

    - name: Print curl version
      debug:
        msg: "curl is installed: {{ curl_check.stdout.split('\n')[0] }}"

    - name: Check unzip installation and version
      command: unzip -v
      register: unzip_check
      changed_when: false
      failed_when: unzip_check.rc != 0

    - name: Print unzip version
      debug:
        msg: "unzip is installed: {{ unzip_check.stdout.split('\n')[0] }}"