- name: Install tools on target machines
  hosts: all
  become: yes

  tasks:
    - name: Enable universe repository (Ubuntu/Debian)
      command: add-apt-repository universe
      when: ansible_os_family == "Debian"

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install tools on Debian/Ubuntu
      apt:
        name:
          - jq
          - curl
          - unzip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install tools on RHEL/CentOS
      yum:
        name:
          - jq
          - curl
          - unzip
        state: present
      when: ansible_os_family == "RedHat"